config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  root 'homes#top'
  get 'homes/about' => 'homes#about'

  namespace :public do
   
    get "search" => 'searches#search'
    resources :items, only: [:index, :show]
    resource :customers, except: [:index, :new, :create, :destroy]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confilm' => 'orders#confilm'
    get 'orders/complete' => 'orders#complete'
    resources :addresses, except: [:new, :show]
    resources :shippings, except: [:new,:show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]


  end


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  namespace :admin do
    get "search" => 'searches#search'
    get "finder" => 'searches#finder'
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, except: [:new, :create, :destroy]
    get 'orders/:id' => 'orders#show'
    resources :order_details, only: [:update]
    patch 'orders/:id' => 'orders#update'



  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shippings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: {Available: false, Invalid: true}

 # def change
    #add_column :customers, :is_deleted, :boolean, default: true, null: false
  #end

  def active_for_authentication?
    super && (self.is_deleted === "Available" )
  end

  def self.looks(searches, words)

        if searches == "perfect_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}")


        elsif searches == "forward_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}%")

        elsif searches == "backword_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "%#{words}")

        else
            @customer = Customer.where("first_name || secound_name LIKE  ?", "%#{words}%")
        end
  end

  validates :first_name, presence: true
  validates :secound_name, presence: true
  validates :first_name_alias, presence: true
  validates :secound_name_alias, presence: true
  validates :zip_code, length: {is: 7}
  validates :address, presence: true
  validates :tel_number, presence: true, numericality: { only_integer: true }
  validates :encrypted_password, presence: true, length: {minimum: 6}
  validates :email, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])

  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

private

  def customer_params
    params.require(:customer).permit(:email, :first_name, :secound_name, :first_name_alias, :secound_name_alias, :zip_code, :address, :tel_number, :is_deleted)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     super(resource)
     public_customers_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end


end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-5">
  <h5><%= @customer.first_name %><%= @customer.secound_name %> さんの会員情報編集</h5>
  <div class="row">
    <div class="col-8 my-2">
      <%= form_with model:@customer,url:admin_customer_path, local:true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
              <td></td>
            </tr>
            <tr>
              <td><%= f.label :氏名 %></td>
              <td>
                <%= f.text_field :first_name, class: 'form-control customer_first_neme' %>
              </td>
              <td>
                <%= f.text_field :secound_name, class: 'form-control customer_secound_name' %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :フリガナ %></td>
              <td>
                <%= f.text_field :first_name_alias, class: 'form-control customer_first_neme_alias' %>
              </td>
              <td>
                <%= f.text_field :secound_name_alias, class: 'form-control customer_secound_name_alias' %>
              </td>
            </tr>
            <tr>
              <td><%= f.label :郵便番号 %></td>
              <td><%= f.text_field :zip_code, class: 'form-control customer_zip_code' %></td>
            </tr>
            <tr>
              <td><%= f.label :住所 %></td>
              <td><%= f.text_area :address, class: 'form-control customer_address' %></td>
            </tr>
            <tr>
              <td><%= f.label :電話番号 %></td>
              <td><%= f.text_field :tel_number, class: 'form-control customer_tel_number' %></td>
            </tr>
            <tr>
              <td><%= f.label :メールアドレス %></td>
              <td><%= f.text_field :email, class: 'form-control customer_email' %></td>
            </tr>
            <tr>
              <td><%= f.label :会員ステータス %></td>
              <td>
                <%= f.radio_button :is_deleted, true %>
                <%= f.label :is_deleted, '有効', value: true %>
                <%= f.radio_button :is_deleted, false %>
                <%= f.label :is_deleted, '退会', value: false %>
              </td>
            </tr>
            <tr>
              <td></td>
              <td><%= f.submit "変更を保存", class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
      

app/views/admin/customers/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-3">
      <h5>会員検索</h5>
      <%= form_with url: admin_search_path, method: :get, local: :true do |f| %>
        <%= f.text_field :word %>
        <%= f.submit "検索" %>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward-match"],["後方一致","backword_match"],["部分一致","partial_match"]]), class: "my-2" %>
      <% end %>
    </div>
    <div class="col-9">
      <h5>会員一覧</h5>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
                <%= link_to admin_customer_path(customer.id) do %>
                  <%= customer.first_name %><%= customer.secound_name %>
                <% end %>
              </td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == 'Invalid' %>退会済
                <% else %>有効
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class='container py-5'>
  <h5><%= @customer.first_name %><%= @customer.secound_name %>さんの会員詳細</h5>
  <div class='row'>
    <div class='col my-2'>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td>
              <%= @customer.first_name %>
              <%= @customer.secound_name %>
            </td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td>
              <%= @customer.first_name_alias %>
              <%= @customer.secound_name_alias %>
            </td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.zip_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.tel_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_deleted == "Invalid" %>退会
              <% else %>有効
              <% end %>
            </td>
          </tr>
          <tr>
            <td></td>
            <td>
              <%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success" %>
              <%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-primary mx-5" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>