config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  root 'homes#top'
  get 'homes/about' => 'homes#about'

  namespace :public do
   
    get "search" => 'searches#search'
    resources :items, only: [:index, :show]
    resource :customers, except: [:index, :new, :create, :destroy]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confilm' => 'orders#confilm'
    get 'orders/complete' => 'orders#complete'
    resources :addresses, except: [:new, :show]
    resources :shippings, except: [:new,:show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]


  end


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  namespace :admin do
    get "search" => 'searches#search'
    get "finder" => 'searches#finder'
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, except: [:new, :create, :destroy]
    get 'orders/:id' => 'orders#show'
    resources :order_details, only: [:update]
    patch 'orders/:id' => 'orders#update'



  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details


 enum method_of_payment:{クレジットカード: 0, 銀行振込: 1}

 enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @orders = Order.all
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    #binding.pry
    @delivery_fee = 800
    @prducts = Item.page(params[:page]).per(2)
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
     @order.order_details.each do |f|
        if @order.status == "入金確認"
          f.update(making_status: "製作待ち")
        elsif
            @order.status == "発送済み"
             f.update(making_status: "発送済み")
        end
      end
    #binding.pry
    redirect_back fallback_location: root_path
  end

  private

  def order_params
  params.require(:order).permit(:shipping_zip_code,:shipping_address,:shipping_name,:delivery_fee,:total_price,:method_of_payment,:status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container py-5">
  <h5>注文履歴詳細</h5>
  <div class="row">
    <div class="col-8 my-2">
      <%= form_with model:@order,url:admin_path, method: :patch,local:true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td>購入者</td>
              <td>
                <%= link_to admin_customer_path(@order.customer) do %>
                  <%= @order.customer.first_name  %><%= @order.customer.secound_name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <td>注文日</td>
              <td><%= @order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
            </tr>
            <tr>
              <td>配送先</td>
              <td>
                〒<%= @order.shipping_zip_code %>
                <%= @order.shipping_address %><%= @order.shipping_name %>
              </td>
            </tr>
            <tr>
              <td>支払方法</td>
              <td><%= @order.method_of_payment %></td>
            </tr>
            <tr>
              <td>注文ステータス</td>
              <td>
                <%= f.select :status,Order.statuses.keys %>
                <%= f.submit "更新",class: "btn btn-success mx-5" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-9">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.current_price.to_s(:delimited) %></td>
              <td><%= order_detail.count %></td>
              <td><%= (order_detail.current_price * order_detail.count) .to_s(:delimited)%></td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail),method: :patch, local:true do |f| %>
                <td>
                  <%= f.select :making_status,OrderDetail.making_statuses.keys %>
                  <%= f.submit "更新",class: "btn btn-success mx-5" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td class="font-weight-bold">商品合計</td>
            <td><%= @order.total_price.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td class="font-weight-bold">送料</td>
            <td><%= @delivery_fee.to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <td class="font-weight-bold">請求金額合計</td>
            <td><%= (@order.total_price.to_i + @delivery_fee.to_i).to_s(:delimited) %>円</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>