config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  root 'homes#top'
  get 'homes/about' => 'homes#about'

  namespace :public do
   
    get "search" => 'searches#search'
    resources :items, only: [:index, :show]
    resource :customers, except: [:index, :new, :create, :destroy]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confilm' => 'orders#confilm'
    get 'orders/complete' => 'orders#complete'
    resources :addresses, except: [:new, :show]
    resources :shippings, except: [:new,:show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]


  end


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  namespace :admin do
    get "search" => 'searches#search'
    get "finder" => 'searches#finder'
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, except: [:new, :create, :destroy]
    get 'orders/:id' => 'orders#show'
    resources :order_details, only: [:update]
    patch 'orders/:id' => 'orders#update'



  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

 def add_tax_price
    (self.price * 1.1).round
 end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shippings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: {Available: false, Invalid: true}

 # def change
    #add_column :customers, :is_deleted, :boolean, default: true, null: false
  #end

  def active_for_authentication?
    super && (self.is_deleted === "Available" )
  end

  def self.looks(searches, words)

        if searches == "perfect_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}")


        elsif searches == "forward_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}%")

        elsif searches == "backword_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "%#{words}")

        else
            @customer = Customer.where("first_name || secound_name LIKE  ?", "%#{words}%")
        end
  end

  validates :first_name, presence: true
  validates :secound_name, presence: true
  validates :first_name_alias, presence: true
  validates :secound_name_alias, presence: true
  validates :zip_code, length: {is: 7}
  validates :address, presence: true
  validates :tel_number, presence: true, numericality: { only_integer: true }
  validates :encrypted_password, presence: true, length: {minimum: 6}
  validates :email, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true


end

app/models/instal.rb
class Instal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  def add_tax_price
    (self.price * 1.1).round
  end

   enum is_deleted: {Available: false, Invalid: true}


  def self.looks(searches, words)
    if searches == "perfect_match"
      @item = Item.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @item = Item.where("name LIKE ?", "%#{words}")

    elsif searches == "backword_match"
      @item = Item.where("name LIKE ?", "#{words}%")

    else
      @Item = Item.where("name LIKE ?", "%#{words}%")
    end
  end



  validates :name, presence: true, uniqueness: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details


 enum method_of_payment:{クレジットカード: 0, 銀行振込: 1}

 enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status:{製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3, 発送済み:4}
  
  

end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer
  
  def address_info
    self.zip_code+self.address+self.name
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if request.referer.include?("admin/customer/:id")
      @orders = Order.find(params[:id])
    else
      @orders = Order.all.page(params[:page])
    end

  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page])
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render "edit"
    end
  end

private

 def item_params
   params.require(:item).permit(:name,:image,:introduction,:price,:genre_id,:is_active)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end





  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :secound_name, :first_name_alias, :secound_name_alias, :zip_code, :address, :tel_number, :is_deleted])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">
  <h5>ジャンル編集</h5>
    <div class="row">
      <div class="col-10 py-5">
        <%= form_with model:@genre, url:admin_genre_path, local:true do |f| %>
          <%= f.label :name, 'ジャンル名' %>
          <%= f.text_field :name,class: "mx-5"%>
          <%= f.submit '変更を保存',class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container py-5">
  <h5>ジャンル一覧・追加</h5>
    <div class="row">
      <div class="col-10 py-5">
        <%= form_with model: @genre,url: admin_genres_path, local:true do |f| %>
          <%= f.label :name, 'ジャンル名' %>
          <%= f.text_field :name, placeholder: "ジャンル名",class: "mx-5" %>
          <%= f.submit "新規登録",class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-5 py-5">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td><%= genre.name %></td>
                <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container py-5">
  <h5>注文履歴一覧</h5>
  <div class="row">
    <div class="col my-2">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= link_to admin_path(order) do %>
                  <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                <% end %>
              </td>
              <td><%= order.customer.first_name %><%= order.customer.secound_name %></td>
              <td><%= order.order_details.count %></td>
              <td><%= order.status %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/items/_finder.html.erb
<%= form_with url: admin_finder_path, method: :get, local: :true do |f| %>
  <h5>商品検索</h5>
  <%= f.text_field :word %>
  <%= f.submit "検索" %>
  <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward-match"],["後方一致","backword_match"],["部分一致","partial_match"]]) %>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container py-5">
  <%= render "layouts/error", obj: @item %>
  <h5>商品編集</h5>
  <div class="row">
    <div class="col-7 mx-auto">
      <%= form_with model: [:admin, @item],local:true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :image, '商品画像' %></td>
              <td><%= f.attachment_field :image, placeholder:"商品画像" %></td>
            </tr>
            <tr>
              <td><%= f.label :name, '商品名' %></td>
              <td><%= f.text_field :name,placeholder:"商品名",class: "form-control item-name" %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, '商品説明' %></td>
              <td><%= f.text_area :introduction,placeholder:"ここに説明文を記述します",class: "form-control item-introduction" %></td>
            </tr>
            <tr>
              <td><%= f.label :genre, 'ジャンル' %></td>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "選択してください"},class: "form-control genre" %></td>
            </tr>
            <tr>
              <td><%= f.label :price, '税抜価格' %></td>
              <td><%= f.text_field :price,placeholder:"価格",class: "form-control price" %></td>
            </tr>
            <tr>
              <td><%= f.label :is_active, '販売ステータス' %></td>
              <td>
                <%= f.radio_button :is_active,true %>
                <%= f.label:is_active, '販売中', value: true %>
                <%= f.radio_button :is_active,false %>
                <%= f.label :is_active, '販売停止中',value: false %>
              </td>
              <td><%= f.submit '変更を保存する',class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
　　</div>
　</div>
</div>

app/views/admin/items/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-3">
      <%= render 'finder' %>
    </div>
    <div class="col-9">
      <h5>
        商品一覧
        <%= link_to "", new_admin_item_path,class: "fas fa-plus-square fa-lg" %>
      </h5>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td><%= item.price.to_s(:delimited) %>円</td>
              <td><%= item.genre.name %></td>
              <% if item.is_active == true %>
                <td>販売中</td>
              <% else %>
                <td>販売停止中</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container py-5">
  <h5>商品新規登録</h5>
  <div class="row">
    <div class="col-7 mx-auto">
      <%= form_with model: @item,url: admin_items_path , local:true do |f| %>
        <table class="table table-borderless">
          <tbody>
            <tr>
              <td><%= f.label :image, '商品画像'%></td>
              <td><%= f.attachment_field :image,placeholder:"商品画像" %></td>
            </tr>
            <tr>
              <td><%= f.label :name, '商品名' %></td>
              <td><%= f.text_field :name,placeholder:"商品名" ,class: "form-control item-name" %></td>
            </tr>
            <tr>
              <td><%= f.label :introduction, '商品説明' %></td>
              <td><%= f.text_area :introduction,placeholder:"ここに説明文を記述します",class: "form-control item-introduction" %></td>
            </tr>
            <tr>
              <td><%= f.label :genre, 'ジャンル'%></td>
              <td><%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "選択してください"},class: "form-control genre" %></td>
            </tr>
            <tr>
              <td><%= f.label :price, '税抜価格' %></td>
              <td><%= f.text_field :price,placeholder:"価格",class: "form-control price" %></td>
            </tr>
            <tr>
              <td><%=f.label :is_active, '販売ステータス' %></td>
              <td>
                <%= f.radio_button :is_active,true %>
                <%=f.label:is_active, '販売中', value: true%>
                <%=f.radio_button :is_active,false%>
                <%=f.label :is_active, '販売停止中',value: false%>
              </td>
              <td><%=f.submit '新規登録',class: "btn btn-success" %></td>
            </tr>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container py-5">
  <h5>商品詳細</h5>
  <div class="row my-5">
    <div class="col-4 mx-5">
      <%= attachment_image_tag @item, :image, :fill,300,300 %>
    </div>
    <div class="col-5">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td>商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td>
              税込価格</br>
              (税抜価格)
            </td>
            <td>
              <%= @item.price.to_s(:delimited) %>
              (<%= @item.add_tax_price.to_s(:delimited) %>)円
            </td>
          </tr>
          <tr>
            <td>販売ステータス</td>
            <% if @item.is_active == true %>
              <td>販売中</td>
            <% else %>
              <td>販売停止中</td>
            <% end %>
            <td>
              <%= link_to "編集する" ,edit_admin_item_path(@item),class: "btn btn-success" %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="containar">
  <div class="row col-8 mx-auto">
    <div class="col-8 offset-2 mx-auto">
      <%= image_tag 'img/About.jpg', size: '600x420' %>
      <p class="text-center my-5">
        ながのCAKEは全国発送可能なケーキ屋さんです。<br>
        お子様からお年寄りの方までお召し上がりいただけるよう、<br>
        様々なバリエーションをご用意しております。<br>
        また、全国へ発送可能ですので、「いつ」でも「どこ」でもご注文いただけます。<br>
        ぜひご注文ください。
      </p>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
 <div class="containar mb-5">
  <div class="row col-8 mx-auto">
    <div class="col-8 offset-2 mx-auto">
      <%= link_to public_items_path do %>
       <%= image_tag 'img/top.jpg', size: '600x420' %>
      <% end %>
      <p class="text-center my-4">
       ようこそ、ながのCAKEへ！<br>
  				 このサイトは、ケーキ販売のECサイトになります。<br>
  				 会員でない方も商品の閲覧はできますが<br>
  				 購入には会員登録が必要になります。
      </p>
      <p class="text-center">↑商品一覧はこの画像をクリックしてね♪↑</p>
    </div>
  </div>
</div>