config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {
  sessions:      'customers/sessions',
  passwords:     'customers/passwords',
  registrations: 'customers/registrations'
}
  root 'homes#top'
  get 'homes/about' => 'homes#about'

  namespace :public do
   
    get "search" => 'searches#search'
    resources :items, only: [:index, :show]
    resource :customers, except: [:index, :new, :create, :destroy]
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confilm' => 'orders#confilm'
    get 'orders/complete' => 'orders#complete'
    resources :addresses, except: [:new, :show]
    resources :shippings, except: [:new,:show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]


  end


  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
  namespace :admin do
    get "search" => 'searches#search'
    get "finder" => 'searches#finder'
    root 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, except: [:new, :create, :destroy]
    get 'orders/:id' => 'orders#show'
    resources :order_details, only: [:update]
    patch 'orders/:id' => 'orders#update'



  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

 def add_tax_price
    (self.price * 1.1).round
 end

end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shippings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: {Available: false, Invalid: true}

 # def change
    #add_column :customers, :is_deleted, :boolean, default: true, null: false
  #end

  def active_for_authentication?
    super && (self.is_deleted === "Available" )
  end

  def self.looks(searches, words)

        if searches == "perfect_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}")


        elsif searches == "forward_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "#{words}%")

        elsif searches == "backword_match"
            @customer = Customer.where("first_name || secound_name LIKE ?", "%#{words}")

        else
            @customer = Customer.where("first_name || secound_name LIKE  ?", "%#{words}%")
        end
  end

  validates :first_name, presence: true
  validates :secound_name, presence: true
  validates :first_name_alias, presence: true
  validates :secound_name_alias, presence: true
  validates :zip_code, length: {is: 7}
  validates :address, presence: true
  validates :tel_number, presence: true, numericality: { only_integer: true }
  validates :encrypted_password, presence: true, length: {minimum: 6}
  validates :email, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true, uniqueness: true


end

app/models/instal.rb
class Instal < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  def add_tax_price
    (self.price * 1.1).round
  end

   enum is_deleted: {Available: false, Invalid: true}


  def self.looks(searches, words)
    if searches == "perfect_match"
      @item = Item.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @item = Item.where("name LIKE ?", "%#{words}")

    elsif searches == "backword_match"
      @item = Item.where("name LIKE ?", "#{words}%")

    else
      @Item = Item.where("name LIKE ?", "%#{words}%")
    end
  end



  validates :name, presence: true, uniqueness: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details


 enum method_of_payment:{クレジットカード: 0, 銀行振込: 1}

 enum status:{入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}




end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum making_status:{製作不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3, 発送済み:4}
  
  

end

app/models/shipping.rb
class Shipping < ApplicationRecord

  belongs_to :customer
  
  def address_info
    self.zip_code+self.address+self.name
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end





  def after_sign_out_path_for(resource)
    if resource == :admin
      new_admin_session_path
    else
      root_path
    end
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :secound_name, :first_name_alias, :secound_name_alias, :zip_code, :address, :tel_number, :is_deleted])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="flex-bottom bg-dark text-white pt-4 pb-3">
  <div class="container-fluid">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight 100m dash!</p>
      </div>
    </div>
    <div class="row">
      <div class="mx-auto">
        <i class="fab fa-facebook-square"></i>
        <i class="fab fa-instagram"></i>
        <i class="fab fa-twitter"></i>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color:#ffffff;">
    <div class="container">
      <span>
        <%= link_to root_path, class: ' nav-link text-light' do %>
          <%= image_tag('img/logo2.jpg', class: 'logo') %>
        <% end %>
      </span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li><%= link_to ' 商品一覧',admin_items_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' 会員一覧',admin_customers_path ,class: 'nav-link text-dark'%></li>
            <li><%= link_to ' 注文履歴一覧', admin_root_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' ジャンル一覧', admin_genres_path ,class: 'nav-link text-dark'%></li>
            <li><%= link_to ' ログアウト', destroy_admin_session_path, method: :delete ,class: 'nav-link text-dark'%></li>
          <% elsif customer_signed_in? %>
            <li><%= link_to ' マイページ', public_customers_path(current_customer),class: 'nav-link text-dark' %></li>
            <li><%= link_to ' 商品一覧', public_items_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' カート',public_cart_items_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' ログアウト', destroy_customer_session_path, method: :delete ,class: 'nav-link text-dark'%></li>
          <% else %>
            <li><%= link_to ' About', homes_about_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' 商品一覧',public_items_path,class: 'nav-link text-dark' %></li>
            <li><%= link_to ' 新規登録',new_customer_registration_path ,class: 'nav-link text-dark'%></li>
            <li><%= link_to ' ログイン', new_customer_session_path ,class: 'nav-link text-dark' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkGithub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <main>
      <%= render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>
    <footer><%= render 'layouts/footer' %></footer>
  </body>
</html>